// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { Barlow_Condensed, Inter } from "next/font/google";
// import ToastProvider from "@/components/shared/toastprovider";
// import { PlanProvider } from "@/components/shared/planprovider";
// import "./globals.css";
// import Navbar from "@/components/shared/Navbar";
// import Footer from "@/components/shared/Footer";


// const barlowCondensed = Barlow_Condensed({
//   variable: "--font-heading",
//   subsets: ["latin"],
//   weight: ["500", "600", "700"],
// });


// const inter = Inter({
//   variable: "--font-body",
//   subsets: ["latin"],
// });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: LayoutProps<"/">) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
//         <planprovider>
//         <Navbar/>
//         {children}
//         </planprovider>

//         <Footer/>
//         </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Oswald, Inter } from "next/font/google";

import "./globals.css";

import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import ToastProvider from "@/components/shared/toastprovider";
import { PlanProvider } from "@/components/shared/planprovider";

const oswald = Oswald({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["500", "600", "700"],
});

const inter = Inter({
  variable: "--font-body",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FitLog",
  description: "Your personal workout planner",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body
        className={`${inter.variable} ${oswald.variable} min-h-full flex flex-col`}
      >
        <PlanProvider>
          <Navbar />

          {children}

          <Footer />

          <ToastProvider />
        </PlanProvider>
      </body>
    </html>
  );
}
